[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "podder"
version = "0.0.1"
authors = [
    { name="Laurent van den Bos", email="laurentvdbos@outlook.com" }
]
readme = "README.md"